# configure slack listener
slack:
  - data/simple-example.yml # simple target path

  - in: example*.xlsx # glob
    out: example.yml # target path

  - in: raw-example*.xlsx
    out:
      format: raw
      path: data/raw-example.xlsx
